language: android
sudo: required
jdk: oraclejdk8

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

env:
 matrix:
 - ANDROID_TARGET=android-27
 global:
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
 components:
 - tools
 - platform-tools
 - build-tools-27.0.1
 - android-27
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 licenses:
     - android-sdk-license-.+
     - '.+'

 before_script:
  - chmod +x gradlew
  - yes | sudo sdkmanager --licenses

 before_install:
  - mkdir "$ANDROID_HOME/licenses" || true


